// src/data/documents.js
export const DOCUMENTS = [
  {
    id: "doc1",
    fileName: "Internet_bill.pdf",
    tagId: "tag1",
    categoryId: "cat1",
    folderIds: ["folder_all", "folder_bills"],
  },
  {
    id: "doc2",
    fileName: "Medical_Report.pdf",
    tagId: "tag2",
    categoryId: "cat3",
    folderIds: ["folder_all", "folder_medical"],
  },
  {
    id: "doc3",
    fileName: "Stocks.pdf",
    tagId: "tag3",
    categoryId: "cat2",
    folderIds: ["folder_all", "folder_finance"],
  },
  {
    id: "doc4",
    fileName: "Hotel_bill.jpg",
    tagId: "tag2",
    categoryId: "cat1",
    folderIds: ["folder_bills"],
  },
];
